sylius_resource:
    resources:
        app.page:
            driver: doctrine/orm
            classes:
                model: App\Entity\Page
                repository: App\Repository\PageRepository
